name: AI Digest (Chinese)

on:
  workflow_dispatch:
  schedule:
    - cron: "17 * * * *"  # 每小时第17分钟

permissions:
  contents: read

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests openai

      - name: News AI digest
        env:
          QWEN_API_BASE: ${{ secrets.QWEN_API_BASE }}
          QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
          QWEN_MODEL: ${{ secrets.QWEN_MODEL }}
          WEWORK_WEBHOOK_URL: ${{ secrets.WEWORK_WEBHOOK_URL }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          NEWS_MAX_INPUT_CHARS: 25000
          NEWS_LLM_MAX_TOKENS: 900
        run: |
          python scripts/news_ai_digest.py
