name: Commit Chinese Summary

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests openai

      - name: Chinese commit summaries (Qwen3 via ModelScope)
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          QWEN_API_BASE: ${{ secrets.QWEN_API_BASE }}
          QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
          QWEN_MODEL: ${{ secrets.QWEN_MODEL }}
          WEWORK_WEBHOOK_URL: ${{ secrets.WEWORK_WEBHOOK_URL }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          MAX_COMMITS: 3
          MAX_DIFF_CHARS: 120000
          MAX_PER_COMMIT_CHARS: 40000
          LLM_MAX_TOKENS: 800
          LLM_TEMPERATURE: 0.7
        run: |
          python scripts/commit_summary.py
